### ISSUE TITLE
Filter by DLCs from owned games?

### ISSUE THREAD

**Issue by Auster-South-Anemoi** [ghorint2t/scripts#1]
Title.
Would it be possible?
Thanks in advance.

**Comment by ghorint2t** [comment]
Sadly, no can do - gog global games listing doesn't include any linking information between DLC and the game it belongs to. You can only know if the entry is a DLC or not - not to which game in particular. That info is probably available somehow through some other API, but you'd need to send a query for every game (or DLC) on the list, which is not feasible for store-wide listing.
