### ISSUE TITLE
[Enhancement] Add 'Also include N/A' option for rating

### ISSUE THREAD

**Issue by DawEdhel** [ghorint2t/scripts#10]
As I understand, N/A entries get treated as 0 rating, so any positive-way predicates, e.g. 3+, 4+ and so on, skip these products undeservedly. In my opinion N/A records should be exceptional in the way that they are not visible if any predicate is provided, unless it's empty or the new option is ticked, both which appends games with unknown rating.

At least, It can help to showcase new heavily-discounted games for user's consideration.

Edit 1: forgot about ordering problem. Yet it's still possible to treat them as 0 for ordering reasons, but not for filtering ones.

**Comment by ghorint2t** [comment]
Actually this is already supported with the current filter; I just forgot to add that to README :) Any numeric filter can also work with a combination of values, joined with OR. For rating to include both 4+ and unrated use "0 >=4" filter. Any non-number separator (comma, space, etc.) works. I've updated the README with this case.
