### ISSUE TITLE
Not working in Chromium browsers

### ISSUE THREAD

**Issue by gitscosh** [ghorint2t/scripts#12]
Hello. This suddenly stopped working for me today. It looks like GOG updated their games page to include widescreen and some other options, and the little icon for your awesome list view is no longer visible.

![vivaldi_6h57QzcS7n](https://user-images.githubusercontent.com/22227871/155224255-9096ceeb-88f2-43c0-adcd-e76e6e216377.png)
![vivaldi_CYSbOZGn9Q](https://user-images.githubusercontent.com/22227871/155224258-1a4224c9-c43f-49bc-855b-99653e29dd3f.png)
![vivaldi_9wL5VsfK8Y](https://user-images.githubusercontent.com/22227871/155224259-8dfb3398-f570-4dd6-bf85-a6114e11cfe9.png)

**Comment by ghorint2t** [comment]
Indeed it seems they've changed some CSS. Fixed.
