### ISSUE TITLE
Broken CSS

### ISSUE THREAD

**Issue by DawEdhel** [ghorint2t/scripts#2]
![Screenshot 2021-03-13 142519](https://user-images.githubusercontent.com/15185758/111028499-101ef080-8408-11eb-9a2b-da21a18a17f7.jpg)

Looks like GOG has recently updated css styles for store page that at least made discounted records' prices to be out of bounds.
Could you look into it?

**Comment by ghorint2t** [comment]
Actually, it was newer version of browsers being less tolerant of my html writing :) Fixed.
