### ISSUE TITLE
"In cart" visibility lag

### ISSUE THREAD

**Issue by DawEdhel** [ghorint2t/scripts#3]
There is an issue when selecting in cart doesn't update the basket visually, despite being there if you refresh the page after.
See the video below:

https://user-images.githubusercontent.com/15185758/112671945-ea680180-8e73-11eb-9e62-2d0ba7b9abfd.mp4

**Comment by ghorint2t** [comment]
Bugs in gog code, eh. They themselves work around them by using string ids rather than int ones  (wonder if they even realize that), so I had to change to strings too. Anyway works now, although it is a bit laggy - need to wait a second until cart status updates.
