### ISSUE TITLE
Enhancement: remember the latest setup values

### ISSUE THREAD

**Issue by DawEdhel** [ghorint2t/scripts#4]
It's kinda went to a point when I'm using same filtering and sorting values over and over.
But these are not getting saved thus requiring to input them again upon reentering.

From a technical standpoint Tampermonkey's storage can be utilized to store custom settings/values.
As it is how does Barefoot Essentials deal with saving user settings, [full script here](https://github.com/DawEdhel/Barefoot-Essentials-Fork/blob/main/BE.js).

**Comment by ghorint2t** [comment]
OK, I've added state saving in browser local storage. Filters, column widths and visibility should now be saved between sessions.

**Comment by DawEdhel** [comment]
Thanks for the implementation. But after some testing I've found several problems:
 - if you first press to expand to the full width before opening the grid itself, it defaults the whole storage as can be seen by browser's inspector.
 - "Hide owned" and "Hide DLCs" checks don't get saved.
 - if some column is set to be sorted, it won't be saved.

**Comment by ghorint2t** [comment]
OK should be all fixed now. I've also added saving the 'show images' option while at it.

**Comment by DawEdhel** [comment]
Yep. I've played around, all cases are fixed and its ready to go.
