### ISSUE TITLE
List not loading?

### ISSUE THREAD

**Issue by Auster-South-Anemoi** [ghorint2t/scripts#5]
It was working without issues yesterday, but now it only shows the frame without loading the titles.
The only thing different since yesterday that I noticed is that the browser I use, Firefox, had a big layout update.
Tried the plugin in a new browser profile but had the same result.
How it looks like (it's darkened because of Dark Reader, which never caused issues with the script):
![image](https://user-images.githubusercontent.com/40811642/120695076-5624a700-c481-11eb-916a-25169693c6cd.png)

**Comment by ghorint2t** [comment]
Apparently GOG API cannot handle more than 5000 games in their store. Page 106 of games fails to load using standard GOG site (even without my script). I originally interpreted failed pages as global error and didn't display any games. I've corrected that now though - 'failed' pages will now be ignored, and the grid will display whatever was possible to download.
