### ISSUE TITLE
Grid not showing all titles

### ISSUE THREAD

**Issue by Auster-South-Anemoi** [ghorint2t/scripts#7]
From what I observed, ever since GOG's staff fixed their API so that their own site could display more than 5000 titles, the script stopped showing all titles. Up to some days ago, the script showed only 3000 and something titles, and now it's at 4374.

**Comment by Auster-South-Anemoi** [comment]
Example of game not showing:
https://www.gog.com/game/bittrip_beat

No filters active, at least that I can see:
![image](https://user-images.githubusercontent.com/40811642/124612356-a1e3bb00-de48-11eb-92cb-0049e96773e4.png)

**Comment by ghorint2t** [comment]
Was just looking into this :)
This time it seems like sort of throttling on GOG's side perhaps? From what I saw, some pages from the bunch requested return an empty set rather than a list of games. I will prepare a fix that will treat such empty results as errors and try, sometime later today.

**Comment by ghorint2t** [comment]
Should be all fixed now, although due to retries initial grid load can take more time.
