### ISSUE TITLE
[New GOG interface] Missing link icon

### ISSUE THREAD

**Issue by DawEdhel** [ghorint2t/scripts#8]
Looks like the new interface is up for everyone, which has broken the script.

**Comment by ghorint2t** [comment]
Not for everyone yet - I still have the old one. Will look into this when it is changed on my end.

**Comment by ghorint2t** [comment]
OK, so apparently it is possible to switch to the new interface by changing a cookie. The script should work with the new one for now, although it is likely more changes on GOG side will happen. They moved from old AngularJS to new Angular 12, yet the topbar menu still works on the old one (because why use one only framework on your page when you can use two). As the grid component I use is for AngularJS only, it won't work once they've fully switched to the new one. I'll consider what to do when that happens; probably will just still load the old framework.

**Comment by DawEdhel** [comment]
Looks like everything is working as usual, beside couple issues:
- The icon seems too bland. Do not remember what was it before, but kinda suspicious.
![Screenshot 2021-12-03 173642](https://user-images.githubusercontent.com/15185758/144621066-0b5c277c-7053-44b0-be68-6e4802e5f3f6.jpg)
![Screenshot 2021-12-03 173729](https://user-images.githubusercontent.com/15185758/144621100-34479dc5-1b10-4651-8e99-a60a348e24b5.jpg)
- At the moment got this single game, but script's grid says it's not owned.
Possible cache issue? Previously bought ones in the past seem marked properly.
![Screenshot 2021-12-03 173843](https://user-images.githubusercontent.com/15185758/144621606-bc15c87a-0a5b-43ea-8892-058c6a90a6d2.jpg)
![Screenshot 2021-12-03 174638](https://user-images.githubusercontent.com/15185758/144621961-b0499c68-0faa-44b1-8275-a1fd02c962a2.jpg)

**Comment by ghorint2t** [comment]
Changed the way of getting owned products to use the API rather than directly query storage; maybe it will help. 
The icon was likely a browser issue (worked in firefox); I've updated the CSS to (I think) make it work on others as well.

**Comment by DawEdhel** [comment]
Updated to the latest:

- > The icon was likely a browser issue (worked in firefox); I've updated the CSS to (I think) make it work on others as well.

The browser was Chrome. As for now it's fixed.

- > Changed the way of getting owned products to use the API rather than directly query storage; maybe it will help.

Went checking: at first it does get marked owned properly, yet do these ids supposed to vary? Maybe it was a comparison issue initially.
![Screenshot 2021-12-05 132816](https://user-images.githubusercontent.com/15185758/144742876-1fb2c386-4727-44d5-a625-64dce41c07b0.jpg)

- While testing out the previous bullet point, noticed this redrawing behaviour. Not sure if it was like that before.

https://user-images.githubusercontent.com/15185758/144743119-7e2b6cd7-1b54-4355-ad7d-a01a2378c63d.mp4

**Comment by ghorint2t** [comment]
IDs do not differ; they might just not have been saved in the storage right away after purchasing. 

As for redrawing, it seems to be a misfeature of the grid component - it somehow wants to recalculate 'stretching' columns width when it is unhidden. It's a minor thing; I don't want to dig into the grid code too much. Note that this will not happen when you manually resize the title column to make its width fixed.

**Comment by DawEdhel** [comment]
Looks like something got changed/broken in a past couple days, but the icon is missing for me again.

Here is the console output when only your script is running within Tampermonkey.
![Screenshot 2022-02-05 142253](https://user-images.githubusercontent.com/15185758/152640054-bd3fa8f9-df13-422f-b84b-fe6f004ec5f9.jpg)

**Comment by ghorint2t** [comment]
Seems to work fine on my end - tested on greasemonkey@firefox and tamper@chrome. In your log, it seems something blocked the polyfill.js script which cascaded into further errors. Perhaps some other user script or a script blocker? On my tests, that script loaded fine and no angular error was shown.

**Comment by DawEdhel** [comment]
Actually sooner today, in the morning I'd tested same page, trying to utilize native filters, and yet nothing worked on the page as well, as I couldn't change mostly anything.
I've found several reports on GOG forums that only english version got broken, thus it was a still server-sided issue.
[1](https://www.gog.com/forum/general/the_what_did_just_break_thread_20/post2614) [2](https://www.gog.com/forum/general/gog_not_working_in_firefox/post22)

At the moment looks like it got fixed, so does the missing link icon.
I'll close this issue, as new interface got broadly spread, and everything looks intact.
