### ISSUE TITLE
[Enhancement] Add 'Show DLC for only owned base games' option

### ISSUE THREAD

**Issue by DawEdhel** [ghorint2t/scripts#9]
What about implementing the title option? Do you have enough info from API to make these connections?

Basically I'm requesting to add a sort of middle ground between showing all DLC and none ones.
The main point of the option is see only currently discounted/newly added/etc. DLC for owned products, that potentially can be interested for an user to get, instead of going through all of them, mostly of which you can't buy anyway until getting a base game first.

**Comment by ghorint2t** [comment]
Unfortunately, the catalog API (both old and new) provides no link between DLCs and their parent game. So the best that could be done is to guess that link by title, but I wouldn't want to do it - the titles do not always match properly. Querying every single game/DLC is not feasible as well. So I'm afraid until GOG changes the catalog data it will not be possible.

**Comment by DawEdhel** [comment]
I've looked around v2 API and noticed these fields that potentially could help to make bridges:
- requiresGames
- isIncludedInGames
- includesGames

Let's take this example: [Brigador](https://www.gogdb.org/products?search=brigador).
- Here both DLCs via API mention requiring base version, while deluxe upgrade also included in its deluxe entry:
[Brigador: Deluxe DLC Upgrade](https://api.gog.com/v2/games/1118047580)
[Brigador Modkit & Map Editor](https://api.gog.com/v2/games/1624719164)
- while base and deluxe versions properly relate back:
[Brigador: Up-Armored Edition](https://api.gog.com/v2/games/1356485086?locale=en-US)
[Brigador: Up-Armored Deluxe](https://api.gog.com/v2/games/1178372828?locale=en-US)

Could these info pieces be enough to establish connections in-between?
Also, I think, various bundles should be coupled with base versions as well, via base game's field 'isIncludedInGames', just in case, as with the above example DLC editor only correlates to the base game, yet it could be installed on deluxe version. Not sure how reliable 'owned' marking is done by GOG itself.

**Comment by ghorint2t** [comment]
This falls under the 'Querying every single game/DLC is not feasible as well.' part. Currently, the catalog is 80+ pages - that's 80+ API queries and takes a few seconds to complete. With an account of 200 games, I'd need to send 200 more to check for possible owned DLCs, and I guess there's some script users with way more than that. I'd rather not do it until GOG adds the information to the catalog API.

**Comment by DawEdhel** [comment]
I see, I'm leaving this issue opened for the future then, if anything related will be changed.
Feel free to close it whenever it'd become too stale.
